### ISSUE TITLE
Automatic re-activate of stalled sync

### ISSUE THREAD

**Issue by jingo76** [bucardo/bucardo#88]
Working with bucardo 5.1.1

My configuration is:
1 master db
2 slave dbs
1 relgroup (3 tables)
2 dbgroups (one for each slave with the same master)
2 syncs (one for each dbgroup) with full copy at startup

Translated in bucardo commands:

bucardo add db mydb name=masterdb host=hostmaster pass=**\* user=***
bucardo add db mydb name=slave1 host=hostslave1 pass=**\* user=***
bucardo add db mydb name=slave2 host=hostslave2 pass=**\* user=***

bucardo add relgroup mygroup t1, t2, t3

bucardo add dbgroup group1 masterdb:source, slave1
bucardo add dbgroup group2 masterdb:source, slave2

bucardo add sync sync1 relgroup=mygroup dbgroup=group1 onetimecopy=1
bucardo add sync sync2 relgroup=mygroup dbgroup=group2 onetimecopy=1

If during the normal operations I shut down the postgres service on the slave2 host I get the following messages in the bucardo log:

(4523) [Thu Oct  2 16:38:49 2014] KID (sync2) Missing slave2_db database handle
(4523) [Thu Oct  2 16:38:49 2014] KID (sync2) Kid 4523 exiting at cleanup_kid. Sync "sync2" Reason: DBI connect('dbname=mydb ;host=xxxxx',xxxxx',...) failed: could not connect to server: Connection refused Is the server running on host "xxxx" (x.x.x.x) and accepting  TCP/IP connections on port 5432? at /usr/local/share/perl5/Bucardo.pm line 5528 Line: 3152 
(29583) [Thu Oct  2 16:38:49 2014] MCP Starting check_sync_health
(29583) [Thu Oct  2 16:38:49 2014] MCP Skipping stalled sync sync2

this message is repeated on a regular basis, while the sync1 continues to work properly

If I start again the service on the slave2 host I get:
(5407) [Thu Oct  2 16:41:12 2014] KID (sync2) New kid, sync "sync2" alive=1 Parent=29593 PID=5407 kicked=1 

the slave2 is then updated BUT, for the time being, the sync2 is not used anymore and it results at Stalled.

-bash-4.1$ bucardo status
PID of Bucardo MCP: 29583
 Name    State    Last good    Time     Last I/D    Last bad    Time  
=======+========+============+========+===========+===========+========
 sync1 | Good   | 16:38:40   | 3m 43s | 0/0       | none      |  
 sync2 | Good   | 16:41:12   | 1m 12s | 0/0       | 16:38:40  | 3m 43s 
-bash-4.1$ bucardo list syncs
Sync "sync1"  Relgroup "mygroup " [Active]
  DB group "group1" masterdb:source slave1:target
Sync "sync2"  Relgroup "mygroup " [Stalled]
  DB group "group2" master:source slave2:target

There is no way to make the sync2 restart working without doing
bucardo stop
sleep 
bucardo start

bucardo restart is not working
-bash-4.1$ bucardo restart
Creating /var/run/bucardo/fullstopbucardo ... Done
Checking for existing processes
Cannot start, PID file "/var/run/bucardo/bucardo.mcp.pid" exists
-bash-4.1$ 

bucardo reload causes a crash
-bash-4.1$ bucardo reload
Waited 30s, but Bucardo never confirmed the reload!
HINT: Pass a longer timeout to the reload_config command or set the
reload_config_timeout configuration setting to wait longer

in the meantime the log reports
(6765) [Thu Oct  2 16:46:16 2014] MCP Warning: Killed (line 6804): Can't call method "do" on an undefined value at /usr/local/share/perl5/Bucardo.pm line 6804.
(6765) [Thu Oct  2 16:46:18 2014] MCP End of cleanup_mcp. Sys time: Thu Oct  2 16:46:18 2014. Database time: 2014-10-02 16:46:18.201674+00

Is it possible to fix it and restore the funcionality of sync2 when the database returns online?

**Comment by FredyKonig** [comment]
I had similar problems with many sync
  bucardo stop   
  bucardo deactivate all
   bucardo validate all
   bucardo activate all
   bucardo kick all
then 
   bucardo list sync
   bucardo start
And then my syncs came back to live! not straight forward!!

**Comment by asierazaceta** [comment]
I found similar problems with bucardo v5.4.1 on Ubuntu 14.04.1LTS
In my case I've got two masters. The one running bucardo is a 24x7 running system, while the other comes off/on-line as we need.
Whenever the second master has been offline for a while, the sync is marked as stalled and trying to reactivate fails with a crash (Error in `Bucardo VAC.': double free or corruption (!prev))
I've just tried @FredyKonig workaround and it worked. Annoying though....

**Comment by mterrien** [comment]
Hi,

Do you have an update regarding this critical issue?
I upgraded from 5.3.1 to 5.4.1 thinking that it would solve this problem but it didn't.
It seems this problem exists since the start of release 5 and it has never been fixed.
bucardo revalidation + start/stop procedure is definitely not satisfying in production.

I upgraded from Bucardo 4 to 5 to solve the delta purge issue causing deadlocks at some point and database to grow. Now this problem seems to be solved but this new one is as critical as the previous one.

**Comment by mterrien** [comment]
I implemented the workaround for those interested.
I use bucardo with 2 servers and 2 different syncs (master/slave bucardo_source, master/master bucardo_latest).

Create a cronned task every 5 minutes for instance as below:
- /etc/cron.d/bucardoRestartIfStalled
```
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin
MAILTO=""
*/5 * * * * root /opt/myproject/setup/bucardoRestartIfStalled.sh
```

- /opt/myProject/bucardoRestartIfStalled.sh
```
#!/bin/bash
BUCARDO_RESTART_LOG=/opt/myproject/setup/bucardoRestart.log
NEEDS_RESTART=`psql -qAt -U postgres -d bucardo -c "select count(*) from bucardo.sync where status='stalled'" | tr -d [:space:]`;

if [ ! -e $BUCARDO_RESTART_LOG ] ;
then
        touch $BUCARDO_RESTART_LOG;
fi

if [ "$NEEDS_RESTART" != "0" ] ;
then
        bucardo deactivate all   | tee -a $BUCARDO_RESTART_LOG
        sleep 5
        bucardo validate all   | tee -a $BUCARDO_RESTART_LOG
        sleep 10
        bucardo activate all   | tee -a $BUCARDO_RESTART_LOG
        sleep 10
        bucardo kick all  | tee -a $BUCARDO_RESTART_LOG
        sleep 10
        bucardo stop   | tee -a $BUCARDO_RESTART_LOG
        sleep 10
        bucardo start   | tee -a $BUCARDO_RESTART_LOG
        sleep 10
        bucardo kick all
        sleep 10
fi

```

**Comment by eacshm** [comment]
Hi,

mterrien, your script get number of sync active?  To fix I look for sync not equal active.

I have the same problem and needed the follow commands to fixed a moment.

bucardo deactivate sync # change stalled to inactive on sync table
bucardo activate sync # don't change status, inactive yet
bucardo validate sync # change inactive to active
bucardo stop sync
bucardo start sync # sync work!

**Comment by mterrien** [comment]
initially the code in my reply was:
`where status='stalled' `
but I modified it to:
`where status**=**'active' `
where it is indeed:
`where status**!=**'active' `

**Comment by jgallinari** [comment]
Hi,

None of the solutions proposed here worked for me.
The only way I found to pass a sync from stalled to active was to remove the sync and then add it again.
bucardo stop
bucardo remove sync my_sync
bucardo add sync my_sync relgroup=my_herd dbs=db1_db:source,db2_db:target
bucardo start

**Comment by gustavovalverde** [comment]
Will this be fixed in bucardo? Just today I realized that if one of the databases gets disconnected the whole process stops; which for a replication system is an overkill, as I then should add another tool that monitors bucardo and also an scripts as the one shown here to keep the process up. 

But, also, if one of the databases goes down for a whole day, i feel like this will stall the whole sync until that database is back up. 

This issues are also related:
#105 
#87 
#85 (as it might happend on the server with the bucardo agent)

P.D.: I see that some of you seggregate the sync in multiple syncs. But I just have 1 sync for a multi-master with 4 databases. If just one is down, the whole sync gets stalled.  Would be a recommendation to have a sync for each database? I think this would cause some data integrity problems if those database connections are not stable.

**Comment by FredyKonig** [comment]
probably not fixed yet. In my case I have a separate script to re-activate the sync (from the commands mentioned above). 
Having multiple server syncs would be ideal ... not sure if it is possible.... yet

**Comment by jonjensen** [comment]
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.
